### ISSUE TITLE
unable to verify server

### ISSUE THREAD

**Issue by jaeblaze1989** [CreeperHost/CreeperHostGui#15]
i had my server listed in the online lobby for a while. but now when i restart my server i get

[minetogetherserver]: unable to do call to server list - will try again in 90 seconds. reason: Unable to verify server.
(with the time increment every time it throws the error)

how to i verify my server? i have checked all the configs and i cant see anything wrong.

**Comment by Cloudhunter** [comment]
Usually this is when the IP your server is sending the request out from - or the IP you are providing - does not have a Minecraft server listening on the port.

Do you have the IP of your server so we can look into this further?

**Comment by jaeblaze1989** [comment]
sure thing. my server ip is 149.167.64.40

**Comment by Cloudhunter** [comment]
Do you have anything in the server-ip field in your server.properties?

**Comment by jaeblaze1989** [comment]
nope it is blank. so i assume it defaults to 0.0.0.0

**Comment by Cloudhunter** [comment]
At this point all the client side stuff should be fine.

We'll see if Paul can add anything to show why it can't verify on the backend.

**Comment by jaeblaze1989** [comment]
Update.   i found out that the Multicraft server wrapper i am using forcibly set the ip in server.properties to 0.0.0.0   after ditching the wrapper and removing 0.0.0.0 it seams to have fixed the issue.

also. Amazing mod. i have always wished there was an in game server list. helps people find servers to play on.    great job

**Comment by Cloudhunter** [comment]
Thanks for the info! Server side we should probably ignore IP's in the local range or 0.0.0.0 if they're sent, so I'll leave this open as something we should do :)

**Comment by CH-Paul-T** [comment]
This should be resolved with additional bind_ip verification on our API in the next update.

**Comment by Buzz1971** [comment]
I too am having this issue woke up this morning to find the same error messages
[minetogetherserver]: unable to do call to server list - will try again in 90 seconds. reason: Unable to verify server
my server.properties for ip=  line is blank am I supposed to place the IP address for my server in there?

**Comment by CH-Paul-T** [comment]
Can you confirm if this is still ongoing? We rolled out a load of updates yesterday and today API end.

**Comment by Cloudhunter** [comment]
Closed as should be fixed

**Comment by Gunner76th** [comment]
Posting reply here for documentation as well as starting a new thread due to current threads age. 

So it looks like this problem is back  and alive. Modpack is https://www.feed-the-beast.com/projects/ftb-interactions FTB Integrations. the server_ip= field in server.properties is empty. the IP and Port used to connect to the server is 107.210.94.69:25565

![image](https://user-images.githubusercontent.com/5566872/57042474-bb6a9600-6c32-11e9-8670-7012f583d070.png)
<details>
  <summary>Click for server.properties information</summary>
#Minecraft server properties<br/>
#Wed May 01 20:54:35 UTC 2019<br/>
spawn-protection=16<br/>
max-tick-time=-1<br/>
query.port=25565<br/>
generator-settings=<br/>
force-gamemode=false<br/>
allow-nether=true<br/>
enforce-whitelist=true<br/>
gamemode=0<br/>
dc_preset=notSet<br/>
enable-query=true<br/>
player-idle-timeout=15<br/>
difficulty=3<br/>
spawn-monsters=true<br/>
op-permission-level=4<br/>
pvp=true<br/>
snooper-enabled=true<br/>
level-type=voidworld<br/>
hardcore=false<br/>
enable-command-block=true<br/>
max-players=20<br/>
network-compression-threshold=256<br/>
resource-pack-sha1=<br/>
max-world-size=29999984<br/>
rcon.port=25575<br/>
server-port=25565<br/>
debug=false<br/>
server-ip=<br/>
spawn-npcs=true<br/>
allow-flight=true<br/>
level-name=world<br/>
view-distance=10<br/>
resource-pack=<br/>
displayname=Team IHOC Presents FTB Interactions Version 1.4.2 https\://discord.gg/0hQAXZIOgrb5RFRG<br/>
discoverability=public<br/>
spawn-animals=true<br/>
white-list=true<br/>
rcon.password=*Redacted*<br/>
generate-structures=true<br/>
online-mode=true<br/>
max-build-height=256<br/>
level-seed=53832741<br/>
use-native-transport=true<br/>
prevent-proxy-connections=false<br/>
enable-rcon=true<br/>
motd=\u00A72Team \u00A7aIHOC \u00A77Presents \u00A71F\u00A72T\u00A74B \u00A73Interactions \u00A75Version 1.4.2<br/>

</details>
