### ISSUE TITLE
Game crashed when clicking server refresh button

### ISSUE THREAD

**Issue by Naxanria** [CreeperHost/CreeperHostGui#224]
https://paste.feed-the-beast.com/view/b09e760a
See https://github.com/FTBTeam/FTB-Omnia/issues/19

**Comment by gigabit101** [comment]
Fixed in Beta5 https://cdn.discordapp.com/attachments/670996283820867604/700024549399461968/minetogether-1.15.2-4.0.0-Beta5.jar

**Comment by Cloudhunter** [comment]
Re-opening as not fixed

**Comment by LatvianModder** [comment]
Still happening a lot https://mcmc.dev/crashes/client/eLQ5cigN5fV4

**Comment by gigabit101** [comment]
This has been fixed in newer builds, You will need to update to the latest version to resolve this issue
