### ISSUE TITLE
Game will not finish loading

### ISSUE THREAD

**Issue by gandalftheblack24** [CreeperHost/CreeperHostGui#234]
I am on Minecraft 1.15.2 and am getting the error "MineTogether (minetogether) encountered an error during the sided_setup event phase javax/xml/bind/annotation/adapters/HexBinaryAdapter"

Log is attached
[latest.log](https://github.com/CreeperHost/CreeperHostGui/files/4499452/latest.log)

**Comment by gigabit101** [comment]
You need to use Java 8 for Modded Minecraft... Java 11 will not work with most mods and even forge

**Comment by NanamiArihara** [comment]
Forge 1.15.2 support Java 11 officially and there is no such "Java 11 will not work with most mods", that's totally nonsense.
You may replace [HexDemicalAdapter](https://github.com/CreeperHost/CreeperHostGui/blob/1.15.2/src/main/java/net/creeperhost/minetogether/paul/Callbacks.java#L452) by something like this:
```java
public String encodeHexString(byte[] byteArray) {
    StringBuilder hexString = new StringBuilder();
    for (int i = 0; i < byteArray.length; i++) {
        hexString.append(byteToHex(byteArray[i]));
    }
    return hexString.toString();
}
```

**Comment by Kynolin** [comment]
@NanamiArihara Have you used a custom version with this code successfully, or was that just a general suggestion to get around the issue?

@gigabit101 I'm currently running FTB Omnia 1.4.0 on both a server and client running Java 11, minus the minetogether mod, so your statement is false. The minetogether mod has problems with Java 11 for the reason mentioned in this issue, and it's not the fault of forge or any other mods. The server I have has been running for about a week or two on Java 11 with the minetogether mod included, while I used Java 8 on the client, but I finally removed it so I could also run the client on Java 11 as well.

This issue should be reopened and addressed. I can't speak to the efficacy of what @NanamiArihara  suggested, but I would assume there's more that could be done than blaming the issue on Java versions. If it can't be, please provide a valid reason.

**Comment by Kynolin** [comment]
That's great to hear. Thank you for committing time to that. I understand Java 8 is what ships with Minecraft, and there's no guarantee Java 11 will work with everything, but my intent is more that it's best to avoid arbitrary limitations when another method could work on both versions (like using print() which works in both Python 2 and 3).

I have very little experience writing in Java, but I would certainly contribute if I find something to be useful. I've mainly been testing different JVMs and server/client performance. On that note, one thing I can mention is that GraalVM (both 8 and 11) has drastically improved performance on my dated server. Flight at creative speed or faster with 170 mods is achievable on an AMD FX-8370 and a SATA SSD. I haven't yet gotten to focus on comparisons between 8/11, or features exclusive to 11, but this is still why I advocate for keeping 11 as an option. It opens up new possibilities for improving server performance and in turn the player experience.

**Comment by NanamiArihara** [comment]
My alternative solution is to add glassfish jaxb runtime in my classpath and I have run FTB Interactions on OpenJDK 11 successfully

________________________________

**Comment by NanamiArihara** [comment]
About efficiency, I edited my code posted before to actual implementation in `javax.xml.bind.DatatypeConverterImpl#printHexBinary` so you can safely replace the 

Also that is the only part makes CreeperHostGui not compatible with newer Java versions

I proposed a pull request for this.

**Comment by covers1624** [comment]
Fixed via https://github.com/CreeperHost/CreeperHostGui/commit/043d8429cec0024a9804edcb5ef0427cffb2fd90

**Comment by Moleculor** [comment]
Is there any chance at all that this bug is still present in MineTogether-1.16.4-4.1.6RC3? (Referring to the issue linked above.) Seems to be the same error message. JDK14.
