### ISSUE TITLE
[Bug]: server listing SB3

### ISSUE THREAD

**Issue by rafalohaki** [CreeperHost/CreeperHostGui#637]
### Describe the bug

Server is not listed to public when trying to set discoverability to public in stoneblock 3

### Steps to reproduce

stoneblock 3 
set
discoverability=public
displayname=namedwadwadwa

### Expected behaviour

server listing

### Version

1.18.2

### Minecraft Version

1.18.2

### ModLoader Version

1.18.2-40.1.84

### Additional Information

thats the only error i found in logs with minetogheter.
minetogether-common.mixins.json does not specify "minVersion" property
 minetogether-forge.mixins.json does not specify "minVersion" property

connection via ip or domain is not a problem

**Comment by covers1624** [comment]
Which MineTogether version are you using?

Can you please provide your full server log?

**Comment by rafalohaki** [comment]
ver 6.0.8
https://mclo.gs/otz2Yry

**Comment by covers1624** [comment]
This should now be resolved.

There was an API bug causing this to occur.

**Comment by rafalohaki** [comment]
i updated server minetogheter version to 6.0.10
and client 6.0.10 too.
checking after 10min and still not shown up in public. here are some info
![image](https://user-images.githubusercontent.com/20607107/200183163-ea2175fd-a6d1-4f78-89e7-67b10b4909bd.png)
![image](https://user-images.githubusercontent.com/20607107/200183178-d66b8bc8-6e4a-4fc4-bd98-5d752b945253.png)
server: 
![image](https://user-images.githubusercontent.com/20607107/200183213-93b498f5-5ad6-41a1-a875-ec413cf578ea.png)
client:
![image](https://user-images.githubusercontent.com/20607107/200183229-8c3af6f4-b3b9-453e-ba13-a5f4ce5d3003.png)
 debug logs. https://mclo.gs/8XpJz9X
normal logs. https://mclo.gs/VOWL6lC

**Comment by rafalohaki** [comment]
will  check after 30min again

**Comment by rafalohaki** [comment]
possible there is error from client side. because me and my friend dont see any public server.

**Comment by rafalohaki** [comment]
got screenshot that it shouldnt be problem on serverside, because he saw all public servers, buut me and my friend dont, so it could be client side problem somewhere. still, we dont know what problem could be becase we reinstalled sb3 modpack 3 times today.

**Comment by ThePaul-T** [comment]
What launcher are you using? MineTogether relies on some metadata in the right place which unofficial implementations may not support, and without the data it does not know what modpack you're in and may not be able to show you servers.

**Comment by rafalohaki** [comment]
i was using ftb launcher first, after updating client with 6.0.8 i was using prism, and was testing it on 6.0.10 too. now i tested it on ftb launcher again. its working.
after reinstall modpack and swaping MineTogether version to latest in ftb launcher, its working.
